export const categories = [
    { id: 'now-showing', label: 'Now Showing' },
    { id: 'coming-soon', label: 'Coming Soon' },
    { id: 'marathons', label: 'Marathons' },
];

function createParameters(isMarathon) {
    return [
        {
            id: 'format', label: 'Screening format',
            options: isMarathon ? [
                { id: 'original', label: 'Original', description: 'Japanese audio with English subtitles', price: 0 },
                { id: 'dubbed', label: 'English dub', description: 'English audio throughout the programme', price: 0 },
            ] : [
                { id: 'standard', label: 'Standard', description: 'Digital screening with English subtitles', price: 0 },
                { id: 'atmos', label: 'Dolby Atmos', description: 'Immersive surround sound with English subtitles', price: 250 },
                { id: 'imax', label: 'IMAX', description: 'Large-format screen with English subtitles', price: 400 },
            ],
        },
        {
            id: 'seat', label: 'Your seat',
            options: [
                { id: 'standard', label: 'Standard', description: 'A comfortable cinema seat', price: 0 },
                { id: 'premium', label: 'Premium', description: 'Central seating with extra legroom', price: isMarathon ? 600 : 300 },
                { id: 'recliner', label: 'Recliner', description: 'A reclining seat with extra space', price: isMarathon ? 900 : 500 },
            ],
        },
    ];
}

export const movies = [
    {
        "id": "moonlit-ronin",
        "category": "now-showing",
        "title": "Moonlit Ronin",
        "description": "A wandering swordsman follows a mysterious light across a world caught between night and dawn.",
        "genre": "Action • Fantasy",
        "age": "16+",
        "duration": "1h 48min",
        "price": 900,
        "image": "movies/moonlit-ronin.webp",
        "imageAlt": "A cloaked swordsman overlooking misty mountains beneath a full moon.",
        "imageWidth": 1024,
        "imageHeight": 1536,
        "availability": "Now showing",
        "featured": true
    },
    {
        "id": "tokyo-echo",
        "category": "now-showing",
        "title": "Tokyo Echo",
        "description": "A late-night radio signal begins predicting events across the city before they happen.",
        "genre": "Sci-Fi • Mystery",
        "age": "12+",
        "duration": "2h 02min",
        "price": 1000,
        "image": "movies/tokyo-echo.webp",
        "imageAlt": "A woman on a rooftop watching a luminous radio tower above a futuristic city.",
        "imageWidth": 1024,
        "imageHeight": 1536,
        "availability": "Now showing",
        "featured": true
    },
    {
        "id": "crimson-sky",
        "category": "now-showing",
        "title": "Crimson Sky",
        "description": "Two young pilots cross forbidden skies in search of a city hidden above the clouds.",
        "genre": "Adventure • Drama",
        "age": "12+",
        "duration": "1h 56min",
        "price": 900,
        "image": "movies/crimson-sky.webp",
        "imageAlt": "Two pilots flying toward a floating city above sunset clouds.",
        "imageWidth": 1024,
        "imageHeight": 1536,
        "availability": "Now showing",
        "featured": true
    },
    {
        "id": "last-sakura",
        "category": "now-showing",
        "title": "Last Sakura",
        "description": "Two friends reunite for one final spring while an old promise quietly changes their future.",
        "genre": "Romance • Drama",
        "age": "12+",
        "duration": "1h 42min",
        "price": 800,
        "image": "movies/last-sakura.webp",
        "imageAlt": "Two friends beside a river beneath a blossoming cherry tree.",
        "imageWidth": 1024,
        "imageHeight": 1536,
        "availability": "Now showing",
        "featured": true
    },
    {
        "id": "ghost-signal",
        "category": "now-showing",
        "title": "Ghost Signal",
        "description": "A forgotten receiver starts carrying messages from a station that officially never existed.",
        "genre": "Horror • Mystery",
        "age": "16+",
        "duration": "1h 51min",
        "price": 1000,
        "image": "movies/ghost-signal.webp",
        "imageAlt": "A vintage radio glowing in a deserted railway signal room at night.",
        "imageWidth": 1024,
        "imageHeight": 1536,
        "availability": "Now showing",
        "featured": true
    },
    {
        "id": "blue-horizon",
        "category": "now-showing",
        "title": "Blue Horizon",
        "description": "A seaside journey turns into a search for a legendary island beyond the edge of every map.",
        "genre": "Adventure • Family",
        "age": "6+",
        "duration": "1h 35min",
        "price": 800,
        "image": "movies/blue-horizon.webp",
        "imageAlt": "A sailboat approaching a green island above a turquoise sea.",
        "imageWidth": 1024,
        "imageHeight": 1536,
        "availability": "Now showing",
        "featured": true
    },
    {
        "id": "paper-moon",
        "category": "now-showing",
        "title": "Paper Moon",
        "description": "A student discovers that the stories she folds from paper continue living after midnight.",
        "genre": "Fantasy • Drama",
        "age": "12+",
        "duration": "1h 46min",
        "price": 900,
        "image": "movies/paper-moon.webp",
        "imageAlt": "A young woman releasing glowing paper cranes into the moonlight.",
        "imageWidth": 1024,
        "imageHeight": 1536,
        "availability": "Now showing",
        "featured": false
    },
    {
        "id": "neon-genesis",
        "category": "now-showing",
        "title": "Neon Genesis",
        "description": "Humanity's last orbital city wakes an ancient machine as the stars begin disappearing.",
        "genre": "Sci-Fi • Action",
        "age": "16+",
        "duration": "2h 12min",
        "price": 1100,
        "image": "movies/neon-genesis.webp",
        "imageAlt": "A giant mechanical guardian and a tiny astronaut above the Earth.",
        "imageWidth": 1024,
        "imageHeight": 1536,
        "availability": "Now showing",
        "featured": false
    },
    {
        "id": "moonlit-first-light",
        "category": "coming-soon",
        "title": "Moonlit Ronin: First Light",
        "description": "Before the moon went dark, a young guardian made a promise that would change the mountain kingdoms.",
        "genre": "Action • Fantasy",
        "age": "16+",
        "duration": "1h 54min",
        "price": 1100,
        "image": "movies/moonlit-ronin.webp",
        "imageAlt": "A cloaked swordsman overlooking misty mountains beneath a full moon.",
        "imageWidth": 1024,
        "imageHeight": 1536,
        "availability": "From November 6",
        "featured": false
    },
    {
        "id": "tokyo-after-midnight",
        "category": "coming-soon",
        "title": "Tokyo Echo: After Midnight",
        "description": "A new voice breaks through the city radio network, inviting one listener to rewrite a forgotten night.",
        "genre": "Sci-Fi • Mystery",
        "age": "12+",
        "duration": "2h 08min",
        "price": 1200,
        "image": "movies/tokyo-echo.webp",
        "imageAlt": "A woman on a rooftop watching a luminous radio tower above a futuristic city.",
        "imageWidth": 1024,
        "imageHeight": 1536,
        "availability": "From November 13",
        "featured": false
    },
    {
        "id": "blue-far-shores",
        "category": "coming-soon",
        "title": "Blue Horizon: Far Shores",
        "description": "An unexpected current carries a young crew toward a chain of islands that appears only at sunrise.",
        "genre": "Adventure • Family",
        "age": "6+",
        "duration": "1h 39min",
        "price": 900,
        "image": "movies/blue-horizon.webp",
        "imageAlt": "A sailboat approaching a green island above a turquoise sea.",
        "imageWidth": 1024,
        "imageHeight": 1536,
        "availability": "From November 20",
        "featured": false
    },
    {
        "id": "paper-new-chapter",
        "category": "coming-soon",
        "title": "Paper Moon: A New Chapter",
        "description": "When her paper birds stop returning, a storyteller follows their trail into a world of unfinished tales.",
        "genre": "Fantasy • Drama",
        "age": "12+",
        "duration": "1h 50min",
        "price": 1000,
        "image": "movies/paper-moon.webp",
        "imageAlt": "A young woman releasing glowing paper cranes into the moonlight.",
        "imageWidth": 1024,
        "imageHeight": 1536,
        "availability": "From November 27",
        "featured": false
    },
    {
        "id": "anime-night",
        "category": "marathons",
        "title": "All Night Anime Marathon",
        "description": "Four anime adventures, interval conversations and a shared big-screen journey that lasts until sunrise.",
        "genre": "Marathon • Adventure",
        "age": "16+",
        "duration": "8h · 4 films",
        "price": 2800,
        "image": "events/anime-night.webp",
        "imageAlt": "Moviegoers watching a luminous nebula in a violet cinema auditorium.",
        "imageWidth": 1024,
        "imageHeight": 1536,
        "availability": "October 17 · 22:00",
        "featured": false
    },
    {
        "id": "classics-night",
        "category": "marathons",
        "title": "Classics on Film",
        "description": "Rediscover two much-loved animated stories in an evening dedicated to the warmth and texture of cinema.",
        "genre": "Double bill • Classics",
        "age": "12+",
        "duration": "4h · 2 films",
        "price": 1800,
        "image": "events/classics-night.webp",
        "imageAlt": "A vintage film projector casting a beam of warm light.",
        "imageWidth": 1536,
        "imageHeight": 1024,
        "availability": "October 24 · 18:00",
        "featured": false
    },
    {
        "id": "premiere-night",
        "category": "marathons",
        "title": "Premiere Night",
        "description": "Step onto the red carpet for two new stories and a conversation with fellow fans between screenings.",
        "genre": "Double bill • Premiere",
        "age": "12+",
        "duration": "4h 30min · 2 films",
        "price": 2400,
        "image": "events/premiere-night.webp",
        "imageAlt": "A red carpet leading to the warmly lit entrance of an art deco cinema.",
        "imageWidth": 1536,
        "imageHeight": 1024,
        "availability": "November 2 · 18:30",
        "featured": false
    }
].map((movie) => ({
    ...movie,
    parameters: createParameters(movie.category === 'marathons'),
}));
