export const categories = [
    { id: 'now-showing', label: 'Now Showing' },
    { id: 'coming-soon', label: 'Coming Soon' },
    { id: 'marathons', label: 'Marathons' },
];

function createParameters(isMarathon) {
    return [
        {
            id: 'format', label: 'Screening format',
            options: isMarathon ? [
                { id: 'original', label: 'Original', description: 'Japanese audio with English subtitles', price: 0 },
                { id: 'dubbed', label: 'English dub', description: 'English audio throughout the programme', price: 0 },
            ] : [
                { id: 'standard', label: 'Standard', description: 'Digital screening with English subtitles', price: 0 },
                { id: 'atmos', label: 'Dolby Atmos', description: 'Immersive surround sound with English subtitles', price: 250 },
                { id: 'imax', label: 'IMAX', description: 'Large-format screen with English subtitles', price: 400 },
            ],
        },
        {
            id: 'seat', label: 'Your seat',
            options: [
                { id: 'standard', label: 'Standard', description: 'A comfortable cinema seat', price: 0 },
                { id: 'premium', label: 'Premium', description: 'Central seating with extra legroom', price: isMarathon ? 600 : 300 },
                { id: 'recliner', label: 'Recliner', description: 'A reclining seat with extra space', price: isMarathon ? 900 : 500 },
            ],
        },
    ];
}

export const movies = [
    {
        "id": "moonlit-ronin",
        "category": "now-showing",
        "title": "Moonlit Ronin",
        "description": "A wandering swordsman follows a mysterious light across a world caught between night and dawn.",
        "genre": "Action • Fantasy",
        "age": "16+",
        "duration": "1h 48min",
        "price": 900,
        "image": "movies/moonlit-ronin.webp",
        "imageAlt": "A cloaked swordsman overlooking misty mountains beneath a full moon.",
        "imageWidth": 1024,
        "imageHeight": 1536,
        "availability": "Now showing",
        "featured": true
    },
    {
        "id": "tokyo-echo",
        "category": "now-showing",
        "title": "Tokyo Echo",
        "description": "A late-night radio signal begins predicting events across the city before they happen.",
        "genre": "Sci-Fi • Mystery",
        "age": "12+",
        "duration": "2h 02min",
        "price": 1000,
        "image": "movies/tokyo-echo.webp",
        "imageAlt": "A woman on a rooftop watching a luminous radio tower above a futuristic city.",
        "imageWidth": 1024,
        "imageHeight": 1536,
        "availability": "Now showing",
        "featured": true
    },
    {
        "id": "crimson-sky",
        "category": "now-showing",
        "title": "Crimson Sky",
        "description": "Two young pilots cross forbidden skies in search of a city hidden above the clouds.",
        "genre": "Adventure • Drama",
        "age": "12+",
        "duration": "1h 56min",
        "price": 900,
        "image": "movies/crimson-sky.webp",
        "imageAlt": "Two pilots flying toward a floating city above sunset clouds.",
        "imageWidth": 1024,
        "imageHeight": 1536,
        "availability": "Now showing",
        "featured": true
    },
    {
        "id": "last-sakura",
        "category": "now-showing",
        "title": "Last Sakura",
        "description": "Two friends reunite for one final spring while an old promise quietly changes their future.",
        "genre": "Romance • Drama",
        "age": "12+",
        "duration": "1h 42min",
        "price": 800,
        "image": "movies/last-sakura.webp",
        "imageAlt": "Two friends beside a river beneath a blossoming cherry tree.",
        "imageWidth": 1024,
        "imageHeight": 1536,
        "availability": "Now showing",
        "featured": true
    },
    {
        "id": "ghost-signal",
        "category": "now-showing",
        "title": "Ghost Signal",
        "description": "A forgotten receiver starts carrying messages from a station that officially never existed.",
        "genre": "Horror • Mystery",
        "age": "16+",
        "duration": "1h 51min",
        "price": 1000,
        "image": "movies/ghost-signal.webp",
        "imageAlt": "A vintage radio glowing in a deserted railway signal room at night.",
        "imageWidth": 1024,
        "imageHeight": 1536,
        "availability": "Now showing",
        "featured": true
    },
    {
        "id": "blue-horizon",
        "category": "now-showing",
        "title": "Blue Horizon",
        "description": "A seaside journey turns into a search for a legendary island beyond the edge of every map.",
        "genre": "Adventure • Family",
        "age": "6+",
        "duration": "1h 35min",
        "price": 800,
        "image": "movies/blue-horizon.webp",
        "imageAlt": "A sailboat approaching a green island above a turquoise sea.",
        "imageWidth": 1024,
        "imageHeight": 1536,
        "availability": "Now showing",
        "featured": true
    },
    {
        "id": "paper-moon",
        "category": "now-showing",
        "title": "Paper Moon",
        "description": "A student discovers that the stories she folds from paper continue living after midnight.",
        "genre": "Fantasy • Drama",
        "age": "12+",
        "duration": "1h 46min",
        "price": 900,
        "image": "movies/paper-moon.webp",
        "imageAlt": "A young woman releasing glowing paper cranes into the moonlight.",
        "imageWidth": 1024,
        "imageHeight": 1536,
        "availability": "Now showing",
        "featured": false
    },
    {
        "id": "neon-genesis",
        "category": "now-showing",
        "title": "Neon Genesis",
        "description": "Humanity's last orbital city wakes an ancient machine as the stars begin disappearing.",
        "genre": "Sci-Fi • Action",
        "age": "16+",
        "duration": "2h 12min",
        "price": 1100,
        "image": "movies/neon-genesis.webp",
        "imageAlt": "A giant mechanical guardian and a tiny astronaut above the Earth.",
        "imageWidth": 1024,
        "imageHeight": 1536,
        "availability": "Now showing",
        "featured": false
    },
    {
        "id": "starlight-express",
        "category": "coming-soon",
        "title": "Starlight Express",
        "description": "A young conductor boards a train that travels between constellations, carrying one last passenger home.",
        "genre": "Adventure • Fantasy",
        "age": "6+",
        "duration": "1h 44min",
        "price": 1000,
        "image": "movies/starlight-express.webp",
        "imageAlt": "A young conductor watching a luminous train cross a bridge among the stars.",
        "imageWidth": 1024,
        "imageHeight": 1536,
        "availability": "From November 6",
        "featured": false
    },
    {
        "id": "ember-heart",
        "category": "coming-soon",
        "title": "Ember Heart",
        "description": "A glassmaker brings a firebird to life and must protect its fading spark before her mountain city turns to ash.",
        "genre": "Fantasy • Adventure",
        "age": "12+",
        "duration": "1h 58min",
        "price": 1100,
        "image": "movies/ember-heart.webp",
        "imageAlt": "A glassmaker holding a glowing firebird above a volcanic mountain city.",
        "imageWidth": 1024,
        "imageHeight": 1536,
        "availability": "From November 13",
        "featured": false
    },
    {
        "id": "glass-garden",
        "category": "coming-soon",
        "title": "The Glass Garden",
        "description": "A botanist discovers a hidden greenhouse where crystal flowers preserve the memories of a vanished town.",
        "genre": "Fantasy • Mystery",
        "age": "12+",
        "duration": "1h 47min",
        "price": 1000,
        "image": "movies/glass-garden.webp",
        "imageAlt": "A botanist exploring a misty greenhouse filled with luminous crystal flowers.",
        "imageWidth": 1024,
        "imageHeight": 1536,
        "availability": "From November 20",
        "featured": false
    },
    {
        "id": "winter-lanterns",
        "category": "coming-soon",
        "title": "Winter Lanterns",
        "description": "Two childhood friends follow a trail of lanterns through their snowbound hometown to finish a promise left behind.",
        "genre": "Romance • Drama",
        "age": "12+",
        "duration": "1h 41min",
        "price": 900,
        "image": "movies/winter-lanterns.webp",
        "imageAlt": "Two friends walking through a snowy mountain village beneath warm lanterns.",
        "imageWidth": 1024,
        "imageHeight": 1536,
        "availability": "From November 27",
        "featured": false
    },
    {
        "id": "deepwater-dreams",
        "category": "coming-soon",
        "title": "Deepwater Dreams",
        "description": "A marine explorer follows a singing whale to an underwater city that wakes only once every hundred years.",
        "genre": "Adventure • Family",
        "age": "6+",
        "duration": "1h 38min",
        "price": 900,
        "image": "movies/deepwater-dreams.webp",
        "imageAlt": "A marine explorer in an underwater dome watching a luminous whale above ancient ruins.",
        "imageWidth": 1024,
        "imageHeight": 1536,
        "availability": "From December 4",
        "featured": false
    },
    {
        "id": "clockwork-city",
        "category": "coming-soon",
        "title": "Clockwork City",
        "description": "A courier races across a mechanical city to restart its missing heartbeat before every street freezes in time.",
        "genre": "Sci-Fi • Adventure",
        "age": "12+",
        "duration": "1h 59min",
        "price": 1100,
        "image": "movies/clockwork-city.webp",
        "imageAlt": "A courier with mechanical wings overlooking a city of brass clock towers.",
        "imageWidth": 1024,
        "imageHeight": 1536,
        "availability": "From December 11",
        "featured": false
    },
    {
        "id": "silent-orbit",
        "category": "coming-soon",
        "title": "Silent Orbit",
        "description": "An astronaut answers a distress call from an empty space station where the final transmission has yet to be sent.",
        "genre": "Sci-Fi • Drama",
        "age": "12+",
        "duration": "2h 06min",
        "price": 1200,
        "image": "movies/silent-orbit.webp",
        "imageAlt": "A lone astronaut floating beside an abandoned ring station above a luminous planet.",
        "imageWidth": 1024,
        "imageHeight": 1536,
        "availability": "From December 18",
        "featured": false
    },
    {
        "id": "forest-spirit",
        "category": "coming-soon",
        "title": "Spirit of the Forest",
        "description": "A young ranger joins a luminous forest guardian to find the spring that keeps an ancient woodland alive.",
        "genre": "Fantasy • Family",
        "age": "6+",
        "duration": "1h 36min",
        "price": 900,
        "image": "movies/forest-spirit.webp",
        "imageAlt": "A young ranger meeting a luminous antlered guardian in an ancient green forest.",
        "imageWidth": 1024,
        "imageHeight": 1536,
        "availability": "From December 25",
        "featured": false
    },
    {
        "id": "anime-night",
        "category": "marathons",
        "title": "All Night Anime Marathon",
        "description": "Four anime adventures, interval conversations and a shared big-screen journey that lasts until sunrise.",
        "genre": "Marathon • Adventure",
        "age": "16+",
        "duration": "8h · 4 films",
        "price": 2800,
        "image": "events/anime-night.webp",
        "imageAlt": "Moviegoers watching a luminous nebula in a violet cinema auditorium.",
        "imageWidth": 1024,
        "imageHeight": 1536,
        "availability": "October 17 · 22:00",
        "featured": false
    },
    {
        "id": "classics-night",
        "category": "marathons",
        "title": "Classics on Film",
        "description": "Rediscover two much-loved animated stories in an evening dedicated to the warmth and texture of cinema.",
        "genre": "Double bill • Classics",
        "age": "12+",
        "duration": "4h · 2 films",
        "price": 1800,
        "image": "events/classics-night.webp",
        "imageAlt": "A vintage film projector casting a beam of warm light.",
        "imageWidth": 1536,
        "imageHeight": 1024,
        "availability": "October 24 · 18:00",
        "featured": false
    },
    {
        "id": "premiere-night",
        "category": "marathons",
        "title": "Premiere Night",
        "description": "Step onto the red carpet for two new stories and a conversation with fellow fans between screenings.",
        "genre": "Double bill • Premiere",
        "age": "12+",
        "duration": "4h 30min · 2 films",
        "price": 2400,
        "image": "events/premiere-night.webp",
        "imageAlt": "A red carpet leading to the warmly lit entrance of an art deco cinema.",
        "imageWidth": 1536,
        "imageHeight": 1024,
        "availability": "November 2 · 18:30",
        "featured": false
    }
].map((movie) => ({
    ...movie,
    parameters: createParameters(movie.category === 'marathons'),
}));
